version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moondreams-backend
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: moondreams-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped