version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moondreams-backend
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
    restart: unless-stopped