version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moondreams-backend
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
    restart: unless-stopped

    # Додаємо обмеження ресурсів
    mem_limit: 4g     # максимум 4 ГБ RAM
    cpus: 2.0          # максимум 2 CPU